telemetry:
  logging:
    level: INFO  # DEBUG, INFO, WARNING, ERROR, FATAL
    encoding: json # console, json

#api:
#  http:
#    ...

routers:
  language:
    - id: default
      models:
        - id: openai
          provider:
            openai:
              api_key: "${env:OPENAI_API_KEY}"
